<a href="https://colab.research.google.com/github/kareemullah123456789/MLE/blob/main/Trees_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [89]:
ls /content/drive/MyDrive/HV

custom_functions.py                      spam.csv
Feature_engineering_and_PCA_Class.ipynb  spam.tsv
HR.csv                                   SVM_Implementation.ipynb
Loading_from_pickle_titanic.ipynb        SVM_Preprocessing.ipynb
loan_approved.csv                        train.csv
Naive_Bayes.ipynb                        Transformer_pickle_demo.ipynb
preprocessing.py                         TreeAlgos_Data_Preprocessing.ipynb
Processed_data.pkl                       Tree_CT.pkl
processing_data.py                       Trees_Implementation.ipynb
__pycache__/


In [90]:
import pickle   # importing pickle for saving and loading machine learning models
from sklearn.model_selection import train_test_split  # importing train_test_split for spliting the data into training and testing
from imblearn.over_sampling import SMOTE  # importing SMOTE for Balancing the Data
import warnings
warnings.filterwarnings('ignore')

In [102]:
import sys
sys.path.append('/content/drive/MyDrive/HV')


In [103]:
import os

base_path = "/content/drive/MyDrive/HV"

In [93]:
from preprocessing import *

In [108]:
with open(os.path.join(base_path, "Tree_CT.pkl"), "rb") as f:
    pre = pickle.load(f)

In [109]:
pre

ColumnTransformer(force_int_remainder_cols=True, n_jobs=None,
                  remainder='passthrough', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('OHE columns',
                                 OneHotEncoder(categories='auto', drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               feature_name_combiner='concat',
                                               handle_unknown='error',
                                               max_categories=None,
                                               min_frequency=None,
                                               sparse_output=True),
                                 ['Busine...
                                                unknown_value=None),
                                 ['OverTime']),
                                ('Standard_scaler',
                                 StandardScaler(copy=True, with_mean=True,
                                                with_std=True),
                                 ['Age', 'DailyRate', 'DistanceFromHome',
                                  'MonthlyRate', 'HourlyRate',
                                  'NumCompaniesWorked', 'TotalWorkingYears',
                                  'YearsAtCompany', 'YearsInCurrentRole',
                                  'YearsSinceLastPromotion',
                                  'YearsWithCurrManager',
                                  'PercentSalaryHike'])],
                  verbose=False, verbose_feature_names_out=True)

In [110]:
with open(os.path.join(base_path,'Processed_data.pkl'),'rb') as f:
    df = pickle.load(f)

In [111]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female  ...                  3                         1   
1       Male  ...                  4                         4   
2       Male  ...                  3                         2   
3     Female  ...                  3                         3   
4       Male  ...                  3                         4   
...      ...  ...                ...                       ...   
1465    Male  ...                  3                         3   
1466    Male  ...                  3                         1   
1467    Male  ...                  4                         2   
1468    Male  ...                  3                         4   
1469    Male  ...                  3                         1   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    0                 8                      0   
1                    1                10                      3   
2                    0                 7                      3   
3                    0                 8                      3   
4                    1                 6                      3   
...                ...               ...                    ...   
1465                 1                17                      3   
1466                 1                 9                      5   
1467                 1                 6                      0   
1468                 0                17                      3   
1469                 0                 6                      3   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  1               6                   4   
1                  3              10                   7   
2                  3               0                   0   
3                  3               8                   7   
4                  3               2                   2   
...              ...             ...                 ...   
1465               3               5                   2   
1466               3               7                   7   
1467              

In [116]:
X = df.drop("Attrition",axis=1)     # Extract the features (all columns except Attritions) from the dataset
y = df["Attrition"].map({"No":0,"Yes":1})  # Extract the target variable from the dataset with converting 0 and 1.

In [117]:
df.Attrition.value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [118]:
# Spliting the data into train and test
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=33)

In [119]:
# Transform the training data using the preprocessor object or PipeLine
processed_x_train = pre.fit_transform(x_train)

In [120]:
processed_x_train

array([[1., 0., 0., ..., 0., 3., 2.],
       [0., 0., 1., ..., 2., 2., 3.],
       [0., 0., 1., ..., 1., 3., 1.],
       ...,
       [0., 1., 0., ..., 0., 2., 3.],
       [0., 0., 1., ..., 1., 3., 3.],
       [0., 0., 1., ..., 1., 0., 2.]])

In [121]:
processed_x_train[0]

array([ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  1.        , -0.3098615 ,  1.3622128 ,  1.16898078,
       -1.33034804,  0.05469197,  2.11675505, -0.30137951, -0.32177888,
       -0.60819028, -0.68968387, -0.03669649, -0.5936842 ,  3.        ,
        1.        ,  4.        ,  2.        ,  4.        ,  3.        ,
        2.        ,  0.        ,  3.        ,  2.        ])

### Model Building

In [122]:
import sklearn
sklearn.set_config(print_changed_only=False)

In [123]:
from sklearn.tree import DecisionTreeClassifier        #importing decision tree from sklearn.tree
dt=DecisionTreeClassifier()             #object creation for decision tree
dt.fit(processed_x_train,y_train)    # sample_weight=sample_weights    #train the model

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=None, splitter='best')

In [124]:
#Prediction
processed_x_test = pre.transform(x_test)
y_pred=dt.predict(processed_x_test)

In [125]:
#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.779891304347826 
Precision: 0.36619718309859156 
Recall Score: 0.41935483870967744 
F1 Score 0.39097744360902253 
Confusion Matrix: 
 [[261  45]
 [ 36  26]]
              precision    recall  f1-score   support

           0       0.88      0.85      0.87       306
           1       0.37      0.42      0.39        62

    accuracy                           0.78       368
   macro avg       0.62      0.64      0.63       368
weighted avg       0.79      0.78      0.79       368



In [126]:
results = pd.DataFrame(index=['Accuracy','F1'])
results['DT/imb'] = [acc,f1]
results

DT/imb
Accuracy  0.779891
F1        0.390977

In [127]:
#Prediction on Training data - Test of overfitting
y_pred1=dt.predict(processed_x_train)

#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_train,y_pred1)
pr = precision_score(y_train,y_pred1)
re = recall_score(y_train,y_pred1)
f1 = f1_score(y_train,y_pred1)
cm = confusion_matrix(y_train,y_pred1)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_train,y_pred1))

Accuracy Score:  1.0 
Precision: 1.0 
Recall Score: 1.0 
F1 Score 1.0 
Confusion Matrix: 
 [[927   0]
 [  0 175]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       927
           1       1.00      1.00      1.00       175

    accuracy                           1.00      1102
   macro avg       1.00      1.00      1.00      1102
weighted avg       1.00      1.00      1.00      1102



In [128]:
results['DT/Train'] = [acc,f1]
results

DT/imb  DT/Train
Accuracy  0.779891       1.0
F1        0.390977       1.0

In [129]:
y_train.value_counts()

Attrition
0    927
1    175
Name: count, dtype: int64

In [130]:
## Data Balancing and Creating Model
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)

dt_bal=DecisionTreeClassifier()
dt_bal.fit(x_smote,y_smote)   #Training the model again with smote balanced data

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=None, splitter='best')

In [131]:
y_smote.value_counts()

Attrition
1    927
0    927
Name: count, dtype: int64

In [132]:
#Prediction
#processed_x_test = pre.transform(x_test)
y_pred=dt_bal.predict(processed_x_test)

In [133]:
#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8152173913043478 
Precision: 0.44642857142857145 
Recall Score: 0.4032258064516129 
F1 Score 0.423728813559322 
Confusion Matrix: 
 [[275  31]
 [ 37  25]]
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       306
           1       0.45      0.40      0.42        62

    accuracy                           0.82       368
   macro avg       0.66      0.65      0.66       368
weighted avg       0.81      0.82      0.81       368



In [134]:
results['DT/Smote'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote
Accuracy  0.779891       1.0  0.815217
F1        0.390977       1.0  0.423729

In [139]:
from sklearn.model_selection import GridSearchCV
#creating dictionary--> key value pair of hyperparameters having key as parameter and values as its values
params = {
    "criterion":("gini", "entropy"), #Split criterion
    "splitter":("best", "random"),  #searches the features for a split
    "max_depth":(list(range(1,20,2))),  #depth of tree range from 1 to 19
    "min_samples_split":[2,5,7],    #[2,5,7,10,12,15]the minimum number of samples required to split internal node
    "min_samples_leaf":list(range(1, 5)), #minimum number of samples required to be at a leaf node,we are passing list which is range from 1 to 19
}


tree_clf = DecisionTreeClassifier()                # object creation for decision tree with random state 3
tree_cv = GridSearchCV(tree_clf, params, scoring="f1", n_jobs=-1, verbose=5, cv=2)

In [140]:
tree_cv.fit(processed_x_train,y_train)    # training data on gridsearch cv
best_params = tree_cv.best_params_    # it will give you best parameters
print(f"Best paramters: {best_params})")   # printing  best parameters

Fitting 2 folds for each of 480 candidates, totalling 960 fits
Best paramters: {'criterion': 'entropy', 'max_depth': 11, 'min_samples_leaf': 4, 'min_samples_split': 5, 'splitter': 'random'})


In [ ]:
##Fitting 5 folds for each of 7524 candidates, totalling 37620 fits ---- takes huge time.

In [141]:
tree_cv.best_params_    # getting best parameters from cv

{'criterion': 'entropy',
 'max_depth': 11,
 'min_samples_leaf': 4,
 'min_samples_split': 5,
 'splitter': 'random'}

In [142]:
# passing best parameter to decision tree
dt_optimal=DecisionTreeClassifier(criterion='gini',max_depth=7,min_samples_leaf=14,min_samples_split=5,splitter='best')
dt_optimal.fit(processed_x_train,y_train)

y_pred=dt_optimal.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8288043478260869 
Precision: 0.48717948717948717 
Recall Score: 0.3064516129032258 
F1 Score 0.37623762376237624 
Confusion Matrix: 
 [[286  20]
 [ 43  19]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       306
           1       0.49      0.31      0.38        62

    accuracy                           0.83       368
   macro avg       0.68      0.62      0.64       368
weighted avg       0.80      0.83      0.81       368



In [143]:
results['DT/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT
Accuracy  0.779891       1.0  0.815217  0.828804
F1        0.390977       1.0  0.423729  0.376238

## Random Forest Implementation

In [144]:
from sklearn.ensemble import RandomForestClassifier   # importing randomforest

rf_clf = RandomForestClassifier() # Assigning RandomForest CLassifier into variable
rf_clf.fit(processed_x_train,y_train)   # training the data
y_pred=rf_clf.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8478260869565217 
Precision: 0.7142857142857143 
Recall Score: 0.16129032258064516 
F1 Score 0.2631578947368421 
Confusion Matrix: 
 [[302   4]
 [ 52  10]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       306
           1       0.71      0.16      0.26        62

    accuracy                           0.85       368
   macro avg       0.78      0.57      0.59       368
weighted avg       0.83      0.85      0.81       368



In [145]:
rf_clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=None,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [146]:
results['RF'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826
F1        0.390977       1.0  0.423729  0.376238  0.263158

In [147]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=5)]      # List Comprehension-using for loop in list
max_features = ['auto', 'sqrt','log2']        # maximum number of features allowed to try in individual tree
max_depth = [int(x) for x in np.linspace(10, 110, num=5)]            # List Comprehension-using for loop in list
max_depth.append(None)
min_samples_split = [5,7,10,13]          # minimum number of samples required to split an internal node
min_samples_leaf = [2, 4]              # minimum number of samples required to be at a leaf node.

#dictionary for hyperparameters
random_grid = {'n_estimators': n_estimators, 'max_features': max_features,
               'max_depth': max_depth, 'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf_clf1 = RandomForestClassifier(random_state=42)   # Loading the model

rf_cv = RandomizedSearchCV(estimator=rf_clf1, scoring='f1',param_distributions= random_grid, cv=2,
                               verbose=2, n_jobs=-1)

In [148]:
np.linspace(200,2000,5)

array([ 200.,  650., 1100., 1550., 2000.])

In [149]:
rf_cv.fit(processed_x_train, y_train)
rf_best_params = rf_cv.best_params_
print(f"Best paramters: {rf_best_params})")

Fitting 2 folds for each of 10 candidates, totalling 20 fits
Best paramters: {'n_estimators': 2000, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 60})


In [151]:
# passing best parameter to randomforest
rf_clf2 = RandomForestClassifier(n_estimators=650,min_samples_leaf=4,min_samples_split=7,max_features="sqrt",max_depth=10)
rf_clf2.fit(processed_x_train, y_train)  # train with tune parameters

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=4,
                       min_samples_split=7, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=650, n_jobs=None,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [152]:
y_pred=rf_clf2.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.845108695652174 
Precision: 0.7777777777777778 
Recall Score: 0.11290322580645161 
F1 Score 0.19718309859154928 
Confusion Matrix: 
 [[304   2]
 [ 55   7]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.91       306
           1       0.78      0.11      0.20        62

    accuracy                           0.85       368
   macro avg       0.81      0.55      0.56       368
weighted avg       0.84      0.85      0.79       368



In [153]:
results['RF/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183

## Bagging

In [154]:
from sklearn.ensemble import BaggingClassifier  #import bagging
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

KNN=KNeighborsClassifier()
LR=LogisticRegression()

model_bagg=BaggingClassifier(estimator=KNN,n_estimators=20) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners

model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

In [155]:
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8342391304347826 
Precision: 0.5384615384615384 
Recall Score: 0.11290322580645161 
F1 Score 0.18666666666666668 
Confusion Matrix: 
 [[300   6]
 [ 55   7]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       306
           1       0.54      0.11      0.19        62

    accuracy                           0.83       368
   macro avg       0.69      0.55      0.55       368
weighted avg       0.79      0.83      0.79       368



In [156]:
results['Bag/KNN'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT   Bag/KNN
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109  0.834239
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183  0.186667

In [157]:
model_bagg

BaggingClassifier(bootstrap=True, bootstrap_features=False,
                  estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                                 metric='minkowski',
                                                 metric_params=None,
                                                 n_jobs=None, n_neighbors=5,
                                                 p=2, weights='uniform'),
                  max_features=1.0, max_samples=1.0, n_estimators=20,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [158]:
model_bagg=BaggingClassifier(estimator=LR,n_estimators=50) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners
model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8695652173913043 
Precision: 0.6590909090909091 
Recall Score: 0.46774193548387094 
F1 Score 0.5471698113207547 
Confusion Matrix: 
 [[291  15]
 [ 33  29]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       306
           1       0.66      0.47      0.55        62

    accuracy                           0.87       368
   macro avg       0.78      0.71      0.74       368
weighted avg       0.86      0.87      0.86       368



In [159]:
results['Bag/LR'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  
Accuracy  0.834239  0.869565  
F1        0.186667  0.547170

In [160]:
model_bagg=BaggingClassifier(estimator=LR,n_estimators=50,max_samples=0.7,max_features=0.7,bootstrap_features=True) ## model objet creation
#base_estimator---> algorithm which you want to pass
#n_estimotors-----> number of base learners
model_bagg.fit(processed_x_train,y_train) ## fitting the model
y_pred=model_bagg.predict(processed_x_test) ## getting the prediction

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.845108695652174 
Precision: 1.0 
Recall Score: 0.08064516129032258 
F1 Score 0.14925373134328357 
Confusion Matrix: 
 [[306   0]
 [ 57   5]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91       306
           1       1.00      0.08      0.15        62

    accuracy                           0.85       368
   macro avg       0.92      0.54      0.53       368
weighted avg       0.87      0.85      0.79       368



In [161]:
results['Bag/LR/Smpl'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  Bag/LR/Smpl  
Accuracy  0.834239  0.869565     0.845109  
F1        0.186667  0.547170     0.149254

### Boosting and XG Boosting

In [162]:
from sklearn.ensemble import GradientBoostingClassifier  # Importing GradientBoostingClassifier
gbm=GradientBoostingClassifier() ## object creation
gbm.fit(processed_x_train,y_train) ## fitting the data

y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8722826086956522 
Precision: 0.7586206896551724 
Recall Score: 0.3548387096774194 
F1 Score 0.4835164835164835 
Confusion Matrix: 
 [[299   7]
 [ 40  22]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.76      0.35      0.48        62

    accuracy                           0.87       368
   macro avg       0.82      0.67      0.71       368
weighted avg       0.86      0.87      0.85       368



In [163]:
gbm

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [164]:
results['GB'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  Bag/LR/Smpl        GB  
Accuracy  0.834239  0.869565     0.845109  0.872283  
F1        0.186667  0.547170     0.149254  0.483516

In [165]:
## Hyperparameter tuning for GradientBoost
# Importing RandomizedSearchCV from sklearn
from sklearn.model_selection import RandomizedSearchCV

# Define Parameters grid for learning_rate, max_depth, n_estimators
param_grid = {
    'learning_rate': [0.01, 0.03, 0.06, 0.1, 0.4, 0.5, 0.6, 0.7],
    'max_depth': [5, 6, 7, 8, 9, 10],
    'n_estimators': [50, 65, 80, 100]
}
GB=GradientBoostingClassifier()  # Assigning GradientBoostingClassifier model into variables

rcv= RandomizedSearchCV(estimator=GB, scoring='f1',refit = True,param_distributions=param_grid, cv=2,
                               verbose=2, n_jobs=-1,n_iter=30)
rcv.fit(processed_x_train,y_train)
rcv.best_params_

Fitting 2 folds for each of 30 candidates, totalling 60 fits


{'n_estimators': 50, 'max_depth': 6, 'learning_rate': 0.6}

In [166]:
GB2=GradientBoostingClassifier(n_estimators=100, max_depth=7, learning_rate=0.4)
GB2.fit(processed_x_train,y_train)

y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8722826086956522 
Precision: 0.7586206896551724 
Recall Score: 0.3548387096774194 
F1 Score 0.4835164835164835 
Confusion Matrix: 
 [[299   7]
 [ 40  22]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.76      0.35      0.48        62

    accuracy                           0.87       368
   macro avg       0.82      0.67      0.71       368
weighted avg       0.86      0.87      0.85       368



In [167]:
results['GB/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  Bag/LR/Smpl        GB    GB/HPT  
Accuracy  0.834239  0.869565     0.845109  0.872283  0.872283  
F1        0.186667  0.547170     0.149254  0.483516  0.483516

## XGBoosting

In [168]:
#!pip install xgboost #installing model XGBOOST
## model creation
from xgboost import XGBClassifier#importing the model library
xgb_r=XGBClassifier() ## object creation
xgb_r.fit(processed_x_train,y_train)# fitting the data
y_pred=xgb_r.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8614130434782609 
Precision: 0.6774193548387096 
Recall Score: 0.3387096774193548 
F1 Score 0.45161290322580644 
Confusion Matrix: 
 [[296  10]
 [ 41  21]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92       306
           1       0.68      0.34      0.45        62

    accuracy                           0.86       368
   macro avg       0.78      0.65      0.69       368
weighted avg       0.84      0.86      0.84       368



In [169]:
xgb_r

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [170]:
results['XGB'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  Bag/LR/Smpl        GB    GB/HPT       XGB  
Accuracy  0.834239  0.869565     0.845109  0.872283  0.872283  0.861413  
F1        0.186667  0.547170     0.149254  0.483516  0.483516  0.451613

In [71]:
#Hyperparameter tuning
param_grid = {'gamma': [0,0.1,0.2,0.4],
              'learning_rate': [0.01, 0.03, 0.06, 0.1],
              'max_depth': [5,6,7,8,9],
              'n_estimators': [50,65,80],
              'reg_alpha': [0,0.1,0.2,0.4],
              'reg_lambda': [0,0.1,0.2]}

XGB=XGBClassifier(random_state=42,verbosity=0,silent=0)  # Assigning XGBClassifier model into variables
rcv= GridSearchCV(estimator=XGB, scoring='f1',refit=True,param_grid=param_grid,  cv=2,
                               verbose=1, n_jobs=-1)
rcv.fit(processed_x_train,y_train)
rcv.best_params_

Fitting 2 folds for each of 2880 candidates, totalling 5760 fits


{'gamma': 0,
 'learning_rate': 0.1,
 'max_depth': 8,
 'n_estimators': 80,
 'reg_alpha': 0.1,
 'reg_lambda': 0}

In [171]:
XGB2=XGBClassifier(reg_lambda= 0.1, reg_alpha= 0.1, n_estimators=50, max_depth=8, learning_rate=0.1, gamma=0)
XGB2.fit(processed_x_train,y_train)
y_pred=XGB2.predict(processed_x_test)#testing

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8668478260869565 
Precision: 0.7407407407407407 
Recall Score: 0.3225806451612903 
F1 Score 0.449438202247191 
Confusion Matrix: 
 [[299   7]
 [ 42  20]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.92       306
           1       0.74      0.32      0.45        62

    accuracy                           0.87       368
   macro avg       0.81      0.65      0.69       368
weighted avg       0.85      0.87      0.84       368



In [172]:
results['XGB/HPT'] = [acc,f1]
results

DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT  \
Accuracy  0.779891       1.0  0.815217  0.828804  0.847826  0.845109   
F1        0.390977       1.0  0.423729  0.376238  0.263158  0.197183   

           Bag/KNN    Bag/LR  Bag/LR/Smpl        GB    GB/HPT       XGB  \
Accuracy  0.834239  0.869565     0.845109  0.872283  0.872283  0.861413   
F1        0.186667  0.547170     0.149254  0.483516  0.483516  0.451613   

           XGB/HPT  
Accuracy  0.866848  
F1        0.449438

In [173]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(processed_x_train,y_train)

y_pred=LR.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.8668478260869565 
Precision: 0.6382978723404256 
Recall Score: 0.4838709677419355 
F1 Score 0.5504587155963303 
Confusion Matrix: 
 [[289  17]
 [ 32  30]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       306
           1       0.64      0.48      0.55        62

    accuracy                           0.87       368
   macro avg       0.77      0.71      0.74       368
weighted avg       0.86      0.87      0.86       368



In [174]:
## Data Balancing and Creating Model
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)
LR.fit(x_smote,y_smote)

y_pred=LR.predict(processed_x_test)#predicting the price

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))


Accuracy Score:  0.779891304347826 
Precision: 0.41739130434782606 
Recall Score: 0.7741935483870968 
F1 Score 0.5423728813559322 
Confusion Matrix: 
 [[239  67]
 [ 14  48]]
              precision    recall  f1-score   support

           0       0.94      0.78      0.86       306
           1       0.42      0.77      0.54        62

    accuracy                           0.78       368
   macro avg       0.68      0.78      0.70       368
weighted avg       0.86      0.78      0.80       368

